# Generated by Django 4.2.7 on 2023-12-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Muscian', '0001_initial'),
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumsform',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Muscian.musician'),
        ),
    ]
