# Generated by Django 4.2.7 on 2023-12-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='./media/image')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_model.brand')),
            ],
        ),
    ]
