# Generated by Django 4.2.7 on 2023-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
