# Generated by Django 4.2.7 on 2023-12-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0003_cars_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=150),
        ),
    ]
