# Generated by Django 4.2.7 on 2023-12-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='already_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
