# Generated by Django 4.2.7 on 2023-12-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0006_order_already_purchased_order_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='already_purchased',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_quantity',
        ),
    ]
